#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

#binary split partition
yabai -m config layout bsp

yabai -m config external_bar               all:39:0     \
                window_border              on           \
                window_border_blur         off          \
                mouse_follows_focus        on           \
                focus_follows_mouse        on           \
                window_placement           second_child \
                window_border_width        4            \
                window_border_radius       11           \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                20           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 8

#disabled apps
yabai -m rule --add app="^(Blender Preferences|Alfred Preferences|Library|Calendar|Photos|Software Update|App Store|Finder|Activity Monitor|Notes|Calculator|Software Update|System Preferences|System Settings)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

